import {
  Ingredient,
  Category,
  Unit,
  Recipe,
  RecipeIngredientItem,
  SubRecipe,
  SubRecipeIngredientItem,
  SalesMenu,
  IngredientPriceHistory,
  AppSettings,
  AuditLog,
  RecipeVersion,
} from './types.ts';

export const initialUnits: Unit[] = [
  { id: 'unit_kg', name: 'Kg', base_unit: 'Gram', conversion_factor: 1000, type: 'WEIGHT', status: 'ACTIVE' },
  { id: 'unit_gram', name: 'Gram', base_unit: 'Gram', conversion_factor: 1, type: 'WEIGHT', status: 'ACTIVE' },
  { id: 'unit_liter', name: 'Liter', base_unit: 'Ml', conversion_factor: 1000, type: 'VOLUME', status: 'ACTIVE' },
  { id: 'unit_ml', name: 'Ml', base_unit: 'Ml', conversion_factor: 1, type: 'VOLUME', status: 'ACTIVE' },
  { id: 'unit_pcs', name: 'Pcs', base_unit: 'Pcs', conversion_factor: 1, type: 'UNIT', status: 'ACTIVE' },
  { id: 'unit_botol', name: 'Botol', base_unit: 'Botol', conversion_factor: 1, type: 'UNIT', status: 'ACTIVE' },
  { id: 'unit_bungkus', name: 'Bungkus', base_unit: 'Bungkus', conversion_factor: 1, type: 'UNIT', status: 'ACTIVE' },
  { id: 'unit_box', name: 'Box', base_unit: 'Box', conversion_factor: 1, type: 'UNIT', status: 'ACTIVE' },
  { id: 'unit_sdm', name: 'Sendok Makan (Sdm)', base_unit: 'Gram', conversion_factor: 15, type: 'WEIGHT', status: 'ACTIVE' },
  { id: 'unit_sdt', name: 'Sendok Teh (Sdt)', base_unit: 'Gram', conversion_factor: 5, type: 'WEIGHT', status: 'ACTIVE' },
  { id: 'unit_portion', name: 'Portion', base_unit: 'Portion', conversion_factor: 1, type: 'PORTION', status: 'ACTIVE' },
];

export const initialCategories: Category[] = [
  // Ingredient Categories
  { id: 'cat_ing_protein', name: 'Daging & Protein', type: 'INGREDIENT', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_ing_produce', name: 'Sayur & Bumbu Segar', type: 'INGREDIENT', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_ing_staples', name: 'Bahan Pokok & Tepung', type: 'INGREDIENT', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_ing_dairy', name: 'Dairy & Telur', type: 'INGREDIENT', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_ing_condiments', name: 'Minyak & Bumbu Dapur', type: 'INGREDIENT', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  // Recipe Categories (Default as specified: Makanan, Minuman, Snack, Dessert, Bakery, Saus, Sambal, Bumbu)
  { id: 'cat_rec_makanan', name: 'Makanan', type: 'RECIPE', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_rec_minuman', name: 'Minuman', type: 'RECIPE', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_rec_snack', name: 'Snack', type: 'RECIPE', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_rec_dessert', name: 'Dessert', type: 'RECIPE', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_rec_bakery', name: 'Bakery', type: 'RECIPE', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_rec_saus', name: 'Saus', type: 'RECIPE', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_rec_sambal', name: 'Sambal', type: 'RECIPE', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_rec_bumbu', name: 'Bumbu', type: 'RECIPE', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  // Menu Categories
  { id: 'cat_menu_main', name: 'Main Course', type: 'MENU', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_menu_beverage', name: 'Beverage', type: 'MENU', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
  { id: 'cat_menu_dessert', name: 'Sweet & Pastry', type: 'MENU', status: 'ACTIVE', created_at: '2026-01-15T08:00:00Z', updated_at: '2026-01-15T08:00:00Z' },
];

export const initialIngredients: Ingredient[] = [
  {
    id: 'ing_ayam',
    code: 'ING-AYM-01',
    name: 'Ayam Fillet / Karkas',
    category_id: 'cat_ing_protein',
    unit_id: 'unit_kg',
    purchase_price: 36000,
    base_unit: 'Gram',
    price_per_base_unit: 36, // 36.000 / 1000 = Rp36/g
    supplier: 'CV Mitra Unggas Segar',
    status: 'ACTIVE',
    notes: 'Karkas ayam segar bersih, disimpan di chiller 2-4 C',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-28T09:30:00Z',
  },
  {
    id: 'ing_beras',
    code: 'ING-BRS-02',
    name: 'Beras Pandan Wangi',
    category_id: 'cat_ing_staples',
    unit_id: 'unit_kg',
    purchase_price: 15500,
    base_unit: 'Gram',
    price_per_base_unit: 15.5,
    supplier: 'Toko Beras Lumbung Padi',
    status: 'ACTIVE',
    notes: 'Beras kualitas premium wangi pulen',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-20T10:00:00Z',
  },
  {
    id: 'ing_tepung',
    code: 'ING-TPG-03',
    name: 'Tepung Terigu Protein Tinggi',
    category_id: 'cat_ing_staples',
    unit_id: 'unit_kg',
    purchase_price: 14000,
    base_unit: 'Gram',
    price_per_base_unit: 14, // 14.000 / 1000 = Rp14/g
    supplier: 'PT Pangan Sumber Makmur',
    status: 'ACTIVE',
    notes: 'Tepung terigu serbaguna untuk crispy batter & cake',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-30T11:15:00Z',
  },
  {
    id: 'ing_minyak',
    code: 'ING-MYK-04',
    name: 'Minyak Goreng Sawit',
    category_id: 'cat_ing_condiments',
    unit_id: 'unit_liter',
    purchase_price: 17500,
    base_unit: 'Ml',
    price_per_base_unit: 17.5,
    supplier: 'Distributor Sembako Nusantara',
    status: 'ACTIVE',
    notes: 'Kemasan pouch 1L atau jerigen food-grade',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-25T08:00:00Z',
  },
  {
    id: 'ing_cabai',
    code: 'ING-CBI-05',
    name: 'Cabai Rawit Merah',
    category_id: 'cat_ing_produce',
    unit_id: 'unit_kg',
    purchase_price: 45000,
    base_unit: 'Gram',
    price_per_base_unit: 45,
    supplier: 'Pasar Induk Kramat Jati',
    status: 'ACTIVE',
    notes: 'Cabai rawit segar pedas menyengat',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-10-01T07:45:00Z',
  },
  {
    id: 'ing_bamer',
    code: 'ING-BMR-06',
    name: 'Bawang Merah Brebes',
    category_id: 'cat_ing_produce',
    unit_id: 'unit_kg',
    purchase_price: 32000,
    base_unit: 'Gram',
    price_per_base_unit: 32,
    supplier: 'Pasar Induk Kramat Jati',
    status: 'ACTIVE',
    notes: 'Kering, bersih, ukuran sedang',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-29T14:20:00Z',
  },
  {
    id: 'ing_baput',
    code: 'ING-BPT-07',
    name: 'Bawang Putih Kating',
    category_id: 'cat_ing_produce',
    unit_id: 'unit_kg',
    purchase_price: 38000,
    base_unit: 'Gram',
    price_per_base_unit: 38,
    supplier: 'Pasar Induk Kramat Jati',
    status: 'ACTIVE',
    notes: 'Aroma wangi tajam khas kating',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-28T16:00:00Z',
  },
  {
    id: 'ing_garam',
    code: 'ING-GRM-08',
    name: 'Garam Beryodium Halus',
    category_id: 'cat_ing_condiments',
    unit_id: 'unit_kg',
    purchase_price: 8000,
    base_unit: 'Gram',
    price_per_base_unit: 8,
    supplier: 'PT Garam Nasional',
    status: 'ACTIVE',
    notes: 'Garam meja butir halus',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-15T08:00:00Z',
  },
  {
    id: 'ing_gula',
    code: 'ING-GLA-09',
    name: 'Gula Pasir Kristal Putih',
    category_id: 'cat_ing_condiments',
    unit_id: 'unit_kg',
    purchase_price: 17500,
    base_unit: 'Gram',
    price_per_base_unit: 17.5,
    supplier: 'Distributor Sembako Nusantara',
    status: 'ACTIVE',
    notes: 'Gula kristal bersih',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-18T10:00:00Z',
  },
  {
    id: 'ing_telur',
    code: 'ING-TLR-10',
    name: 'Telur Ayam Negeri',
    category_id: 'cat_ing_dairy',
    unit_id: 'unit_kg',
    purchase_price: 29000,
    base_unit: 'Gram',
    price_per_base_unit: 29,
    supplier: 'Peternakan Jaya Mandiri',
    status: 'ACTIVE',
    notes: '1 Kg berisi kira-kira 16 butir telur segar',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-30T09:00:00Z',
  },
  {
    id: 'ing_susu',
    code: 'ING-SSU-11',
    name: 'Susu UHT Full Cream',
    category_id: 'cat_ing_dairy',
    unit_id: 'unit_liter',
    purchase_price: 21000,
    base_unit: 'Ml',
    price_per_base_unit: 21,
    supplier: 'PT Dairy Star Indonesia',
    status: 'ACTIVE',
    notes: 'Karton 1 Liter suhu ruang',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-22T13:00:00Z',
  },
  {
    id: 'ing_keju',
    code: 'ING-KJU-12',
    name: 'Keju Cheddar Block',
    category_id: 'cat_ing_dairy',
    unit_id: 'unit_kg',
    purchase_price: 110000,
    base_unit: 'Gram',
    price_per_base_unit: 110,
    supplier: 'PT Dairy Star Indonesia',
    status: 'ACTIVE',
    notes: 'Block keju gurih mudah diparut',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-26T15:00:00Z',
  },
  {
    id: 'ing_mie_basah',
    code: 'ING-MIE-13',
    name: 'Mie Telur Basah Segar',
    category_id: 'cat_ing_staples',
    unit_id: 'unit_kg',
    purchase_price: 18000,
    base_unit: 'Gram',
    price_per_base_unit: 18,
    supplier: 'Pabrik Mie Barokah',
    status: 'ACTIVE',
    notes: 'Mie basah tanpa bahan pengawet',
    created_at: '2026-02-01T08:00:00Z',
    updated_at: '2026-09-27T08:00:00Z',
  },
  {
    id: 'ing_cokelat_bubuk',
    code: 'ING-CKL-14',
    name: 'Dark Cocoa Powder Murni',
    category_id: 'cat_ing_staples',
    unit_id: 'unit_kg',
    purchase_price: 95000,
    base_unit: 'Gram',
    price_per_base_unit: 95,
    supplier: 'Toko Bahan Kue Sejahtera',
    status: 'ACTIVE',
    notes: 'Kakao bubuk murni aroma intens',
    created_at: '2026-02-05T08:00:00Z',
    updated_at: '2026-09-25T11:00:00Z',
  }
];

export const initialSubRecipes: SubRecipe[] = [
  {
    id: 'sub_sambal_bawang',
    code: 'SUB-SMB-01',
    name: 'Sambal Bawang Spesial',
    yield_quantity: 20,
    yield_unit: 'Portion',
    total_cost: 29500,
    cost_per_unit: 1475,
    status: 'ACTIVE',
    ingredients: [
      { id: 'sri_1', sub_recipe_id: 'sub_sambal_bawang', ingredient_id: 'ing_cabai', ingredient_name: 'Cabai Rawit Merah', quantity: 300, unit: 'Gram', cost: 13500 },
      { id: 'sri_2', sub_recipe_id: 'sub_sambal_bawang', ingredient_id: 'ing_baput', ingredient_name: 'Bawang Putih Kating', quantity: 150, unit: 'Gram', cost: 5700 },
      { id: 'sri_3', sub_recipe_id: 'sub_sambal_bawang', ingredient_id: 'ing_minyak', ingredient_name: 'Minyak Goreng Sawit', quantity: 500, unit: 'Ml', cost: 8750 },
      { id: 'sri_4', sub_recipe_id: 'sub_sambal_bawang', ingredient_id: 'ing_garam', ingredient_name: 'Garam Beryodium Halus', quantity: 30, unit: 'Gram', cost: 240 },
      { id: 'sri_5', sub_recipe_id: 'sub_sambal_bawang', ingredient_id: 'ing_gula', ingredient_name: 'Gula Pasir Kristal Putih', quantity: 75, unit: 'Gram', cost: 1310 },
    ],
    created_at: '2026-01-20T09:00:00Z',
    updated_at: '2026-09-28T10:00:00Z',
  }
];

export const initialRecipes: Recipe[] = [
  {
    id: 'rec_ayam_geprek',
    code: 'REC-AGP-01',
    name: 'Ayam Geprek Sambal Bawang',
    category_id: 'cat_rec_makanan',
    photo_url: '/src/assets/images/dish_ayam_geprek_1791109817096.jpg',
    description: 'Ayam goreng crispy tepung gurih digeprek bersama racikan sambal bawang segar panas.',
    yield_quantity: 10,
    yield_unit: 'Portion',
    prep_time: 25,
    cook_time: 20,
    instructions: '1. Marinasi potongan ayam dengan bumbu bawang putih dan garam 15 menit.\n2. Balurkan ke adonan tepung kering dan celupan air es dua kali.\n3. Goreng dalam minyak panas 170°C hingga keemasan.\n4. Geprek panas-panas bersama 1 porsi Sambal Bawang Culinova.',
    notes: 'Gunakan minyak bersuhu stabil agar kulit crispy renyah tahan lama.',
    status: 'ACTIVE',
    active_version_id: 'ver_agp_2',
    total_ingredient_cost: 87000,
    hpp_per_portion: 8700,
    target_food_cost_pct: 35,
    selling_price: 25000,
    food_cost_pct: 34.8,
    gross_profit: 16300,
    margin_pct: 65.2,
    created_at: '2026-01-22T10:00:00Z',
    updated_at: '2026-09-30T14:00:00Z',
    ingredients: [
      { id: 'ri_agp_1', recipe_id: 'rec_ayam_geprek', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_ayam', ingredient_name: 'Ayam Fillet / Karkas', quantity: 1500, unit: 'Gram', unit_price: 36, cost: 54000, percentage: 62.0, created_at: '2026-01-22T10:00:00Z' },
      { id: 'ri_agp_2', recipe_id: 'rec_ayam_geprek', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_tepung', ingredient_name: 'Tepung Terigu Protein Tinggi', quantity: 500, unit: 'Gram', unit_price: 14, cost: 7000, percentage: 8.0, created_at: '2026-01-22T10:00:00Z' },
      { id: 'ri_agp_3', recipe_id: 'rec_ayam_geprek', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_minyak', ingredient_name: 'Minyak Goreng Sawit', quantity: 400, unit: 'Ml', unit_price: 17.5, cost: 7000, percentage: 8.0, created_at: '2026-01-22T10:00:00Z' },
      { id: 'ri_agp_4', recipe_id: 'rec_ayam_geprek', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_telur', ingredient_name: 'Telur Ayam Negeri', quantity: 125, unit: 'Gram', unit_price: 29, cost: 3625, percentage: 4.2, created_at: '2026-01-22T10:00:00Z' },
      { id: 'ri_agp_5', recipe_id: 'rec_ayam_geprek', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_garam', ingredient_name: 'Garam Beryodium Halus', quantity: 20, unit: 'Gram', unit_price: 8, cost: 160, percentage: 0.2, created_at: '2026-01-22T10:00:00Z' },
      { id: 'ri_agp_6', recipe_id: 'rec_ayam_geprek', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_baput', ingredient_name: 'Bawang Putih Kating', quantity: 60, unit: 'Gram', unit_price: 38, cost: 2280, percentage: 2.6, created_at: '2026-01-22T10:00:00Z' },
      { id: 'ri_agp_7', recipe_id: 'rec_ayam_geprek', ingredient_type: 'SUB_RECIPE', ingredient_id: 'sub_sambal_bawang', ingredient_name: 'Sambal Bawang Spesial', quantity: 10, unit: 'Portion', unit_price: 1475, cost: 14750, percentage: 17.0, created_at: '2026-01-22T10:00:00Z' },
    ],
    versions: [
      {
        id: 'ver_agp_1',
        recipe_id: 'rec_ayam_geprek',
        version_number: 1,
        version_name: 'Versi Original Standard',
        hpp: 91500,
        hpp_per_portion: 9150,
        change_notes: 'Resep awal porsi ayam 1700g per 10 porsi',
        ingredients_snapshot: [],
        status: 'ARCHIVED',
        created_at: '2026-01-22T10:00:00Z',
      },
      {
        id: 'ver_agp_2',
        recipe_id: 'rec_ayam_geprek',
        version_number: 2,
        version_name: 'Optimalisasi Tepung Crispy & Sambal',
        hpp: 87000,
        hpp_per_portion: 8700,
        change_notes: 'Penyesuaian porsi ayam menjadi 1500g dan integrasi sub-recipe sambal',
        ingredients_snapshot: [],
        status: 'ACTIVE',
        created_at: '2026-09-30T14:00:00Z',
      }
    ]
  },
  {
    id: 'rec_nasi_goreng',
    code: 'REC-NSG-02',
    name: 'Nasi Goreng Spesial Resto',
    category_id: 'cat_rec_makanan',
    photo_url: '/src/assets/images/dish_nasi_goreng_1791109832554.jpg',
    description: 'Nasi goreng aromatic khas dengan bumbu racik, telur ceplok dan suwiran ayam gurih.',
    yield_quantity: 8,
    yield_unit: 'Portion',
    prep_time: 15,
    cook_time: 15,
    instructions: '1. Tumis bawang merah dan bawang putih cincang hingga harum.\n2. Masukkan telur, orak-arik matang.\n3. Masukkan nasi pera dingin, bumbui garam, gula, dan kecap.\n4. Aduk dengan api besar (wok hei) sampai rata dan harum.',
    notes: 'Wajib gunakan nasi pera yang didiamkan semalam di chiller.',
    status: 'ACTIVE',
    active_version_id: 'ver_nsg_1',
    total_ingredient_cost: 65600,
    hpp_per_portion: 8200,
    target_food_cost_pct: 32,
    selling_price: 26000,
    food_cost_pct: 31.5,
    gross_profit: 17800,
    margin_pct: 68.5,
    created_at: '2026-02-10T11:00:00Z',
    updated_at: '2026-09-28T16:00:00Z',
    ingredients: [
      { id: 'ri_nsg_1', recipe_id: 'rec_nasi_goreng', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_beras', ingredient_name: 'Beras Pandan Wangi', quantity: 1200, unit: 'Gram', unit_price: 15.5, cost: 18600, percentage: 28.3, created_at: '2026-02-10T11:00:00Z' },
      { id: 'ri_nsg_2', recipe_id: 'rec_nasi_goreng', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_ayam', ingredient_name: 'Ayam Fillet / Karkas', quantity: 600, unit: 'Gram', unit_price: 36, cost: 21600, percentage: 32.9, created_at: '2026-02-10T11:00:00Z' },
      { id: 'ri_nsg_3', recipe_id: 'rec_nasi_goreng', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_telur', ingredient_name: 'Telur Ayam Negeri', quantity: 500, unit: 'Gram', unit_price: 29, cost: 14500, percentage: 22.1, created_at: '2026-02-10T11:00:00Z' },
      { id: 'ri_nsg_4', recipe_id: 'rec_nasi_goreng', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_bamer', ingredient_name: 'Bawang Merah Brebes', quantity: 120, unit: 'Gram', unit_price: 32, cost: 3840, percentage: 5.8, created_at: '2026-02-10T11:00:00Z' },
      { id: 'ri_nsg_5', recipe_id: 'rec_nasi_goreng', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_baput', ingredient_name: 'Bawang Putih Kating', quantity: 80, unit: 'Gram', unit_price: 38, cost: 3040, percentage: 4.6, created_at: '2026-02-10T11:00:00Z' },
      { id: 'ri_nsg_6', recipe_id: 'rec_nasi_goreng', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_minyak', ingredient_name: 'Minyak Goreng Sawit', quantity: 200, unit: 'Ml', unit_price: 17.5, cost: 3500, percentage: 5.3, created_at: '2026-02-10T11:00:00Z' },
      { id: 'ri_nsg_7', recipe_id: 'rec_nasi_goreng', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_garam', ingredient_name: 'Garam Beryodium Halus', quantity: 20, unit: 'Gram', unit_price: 8, cost: 160, percentage: 0.2, created_at: '2026-02-10T11:00:00Z' },
      { id: 'ri_nsg_8', recipe_id: 'rec_nasi_goreng', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_gula', ingredient_name: 'Gula Pasir Kristal Putih', quantity: 20, unit: 'Gram', unit_price: 17.5, cost: 350, percentage: 0.5, created_at: '2026-02-10T11:00:00Z' },
    ],
    versions: [
      {
        id: 'ver_nsg_1',
        recipe_id: 'rec_nasi_goreng',
        version_number: 1,
        version_name: 'Standard Resto V1',
        hpp: 65600,
        hpp_per_portion: 8200,
        change_notes: 'Formula standard nasi goreng spesial 8 porsi',
        ingredients_snapshot: [],
        status: 'ACTIVE',
        created_at: '2026-02-10T11:00:00Z',
      }
    ]
  },
  {
    id: 'rec_mie_ayam',
    code: 'REC-MAY-03',
    name: 'Mie Ayam Komplit Gurih',
    category_id: 'cat_rec_makanan',
    photo_url: '/src/assets/images/dish_mie_ayam_1791109845039.jpg',
    description: 'Mie basah kenyal dengan topping ayam kecap manis gurih, kuah kaldu harum dan pangsit.',
    yield_quantity: 6,
    yield_unit: 'Portion',
    prep_time: 30,
    cook_time: 25,
    instructions: '1. Rebus ayam potong dadu dengan bumbu kecap, bawang, dan rempah.\n2. Rebus mie telur basah 1-2 menit hingga al dente.\n3. Beri minyak bumbu di dasar mangkuk, masukkan mie panas lalu aduk.\n4. Beri topping ayam kecap, sawi hijau, dan kuah kaldu.',
    notes: 'Kuah kaldu disajikan terpisah dalam mangkok kecil.',
    status: 'ACTIVE',
    active_version_id: 'ver_may_1',
    total_ingredient_cost: 54900,
    hpp_per_portion: 9150,
    target_food_cost_pct: 35,
    selling_price: 27000,
    food_cost_pct: 33.9,
    gross_profit: 17850,
    margin_pct: 66.1,
    created_at: '2026-02-15T14:00:00Z',
    updated_at: '2026-09-29T10:00:00Z',
    ingredients: [
      { id: 'ri_may_1', recipe_id: 'rec_mie_ayam', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_mie_basah', ingredient_name: 'Mie Telur Basah Segar', quantity: 900, unit: 'Gram', unit_price: 18, cost: 16200, percentage: 29.5, created_at: '2026-02-15T14:00:00Z' },
      { id: 'ri_may_2', recipe_id: 'rec_mie_ayam', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_ayam', ingredient_name: 'Ayam Fillet / Karkas', quantity: 700, unit: 'Gram', unit_price: 36, cost: 25200, percentage: 45.9, created_at: '2026-02-15T14:00:00Z' },
      { id: 'ri_may_3', recipe_id: 'rec_mie_ayam', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_bamer', ingredient_name: 'Bawang Merah Brebes', quantity: 100, unit: 'Gram', unit_price: 32, cost: 3200, percentage: 5.8, created_at: '2026-02-15T14:00:00Z' },
      { id: 'ri_may_4', recipe_id: 'rec_mie_ayam', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_baput', ingredient_name: 'Bawang Putih Kating', quantity: 80, unit: 'Gram', unit_price: 38, cost: 3040, percentage: 5.5, created_at: '2026-02-15T14:00:00Z' },
      { id: 'ri_may_5', recipe_id: 'rec_mie_ayam', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_minyak', ingredient_name: 'Minyak Goreng Sawit', quantity: 250, unit: 'Ml', unit_price: 17.5, cost: 4375, percentage: 8.0, created_at: '2026-02-15T14:00:00Z' },
      { id: 'ri_may_6', recipe_id: 'rec_mie_ayam', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_gula', ingredient_name: 'Gula Pasir Kristal Putih', quantity: 60, unit: 'Gram', unit_price: 17.5, cost: 1050, percentage: 1.9, created_at: '2026-02-15T14:00:00Z' },
      { id: 'ri_may_7', recipe_id: 'rec_mie_ayam', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_garam', ingredient_name: 'Garam Beryodium Halus', quantity: 20, unit: 'Gram', unit_price: 8, cost: 160, percentage: 0.3, created_at: '2026-02-15T14:00:00Z' },
    ],
    versions: [
      {
        id: 'ver_may_1',
        recipe_id: 'rec_mie_ayam',
        version_number: 1,
        version_name: 'Batch Standard Mie Ayam',
        hpp: 54900,
        hpp_per_portion: 9150,
        change_notes: 'Resep mie basah 6 porsi kenyal',
        ingredients_snapshot: [],
        status: 'ACTIVE',
        created_at: '2026-02-15T14:00:00Z',
      }
    ]
  },
  {
    id: 'rec_chocolate_cake',
    code: 'REC-CKT-04',
    name: 'Artisan Dark Chocolate Fudge Cake',
    category_id: 'cat_rec_dessert',
    photo_url: '/src/assets/images/dish_chocolate_cake_1791109868136.jpg',
    description: 'Cake cokelat fudge lembut dilapisi dark ganache mewah dengan aroma kakao murni.',
    yield_quantity: 12,
    yield_unit: 'Slice',
    prep_time: 35,
    cook_time: 45,
    instructions: '1. Lelehkan dark cocoa powder dengan susu hangat.\n2. Kocok telur dan gula sampai mengembang pucat.\n3. Ayak tepung terigu, campurkan bergantian dengan cairan cokelat.\n4. Panggang 175°C selama 40 menit sampai matang merata.',
    notes: 'Potong dalam kondisi dingin agar potongan slice rapi tajam.',
    status: 'ACTIVE',
    active_version_id: 'ver_ckt_1',
    total_ingredient_cost: 114875,
    hpp_per_portion: 9573,
    target_food_cost_pct: 28,
    selling_price: 35000,
    food_cost_pct: 27.4,
    gross_profit: 25427,
    margin_pct: 72.6,
    created_at: '2026-03-01T09:00:00Z',
    updated_at: '2026-09-25T11:00:00Z',
    ingredients: [
      { id: 'ri_ckt_1', recipe_id: 'rec_chocolate_cake', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_tepung', ingredient_name: 'Tepung Terigu Protein Tinggi', quantity: 400, unit: 'Gram', unit_price: 14, cost: 5600, percentage: 4.9, created_at: '2026-03-01T09:00:00Z' },
      { id: 'ri_ckt_2', recipe_id: 'rec_chocolate_cake', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_cokelat_bubuk', ingredient_name: 'Dark Cocoa Powder Murni', quantity: 250, unit: 'Gram', unit_price: 95, cost: 23750, percentage: 20.7, created_at: '2026-03-01T09:00:00Z' },
      { id: 'ri_ckt_3', recipe_id: 'rec_chocolate_cake', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_telur', ingredient_name: 'Telur Ayam Negeri', quantity: 600, unit: 'Gram', unit_price: 29, cost: 17400, percentage: 15.1, created_at: '2026-03-01T09:00:00Z' },
      { id: 'ri_ckt_4', recipe_id: 'rec_chocolate_cake', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_gula', ingredient_name: 'Gula Pasir Kristal Putih', quantity: 450, unit: 'Gram', unit_price: 17.5, cost: 7875, percentage: 6.9, created_at: '2026-03-01T09:00:00Z' },
      { id: 'ri_ckt_5', recipe_id: 'rec_chocolate_cake', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_susu', ingredient_name: 'Susu UHT Full Cream', quantity: 500, unit: 'Ml', unit_price: 21, cost: 10500, percentage: 9.1, created_at: '2026-03-01T09:00:00Z' },
      { id: 'ri_ckt_6', recipe_id: 'rec_chocolate_cake', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_keju', ingredient_name: 'Keju Cheddar Block', quantity: 200, unit: 'Gram', unit_price: 110, cost: 22000, percentage: 19.2, created_at: '2026-03-01T09:00:00Z' },
      { id: 'ri_ckt_7', recipe_id: 'rec_chocolate_cake', ingredient_type: 'INGREDIENT', ingredient_id: 'ing_minyak', ingredient_name: 'Minyak Goreng Sawit', quantity: 150, unit: 'Ml', unit_price: 17.5, cost: 2625, percentage: 2.3, created_at: '2026-03-01T09:00:00Z' },
      { id: 'ri_ckt_8', recipe_id: 'rec_chocolate_cake', ingredient_type: 'SUB_RECIPE', ingredient_id: 'sub_sambal_bawang', ingredient_name: 'Garnish / Add-on Spec', quantity: 0, unit: 'Portion', unit_price: 1475, cost: 0, percentage: 0, created_at: '2026-03-01T09:00:00Z' },
    ],
    versions: [
      {
        id: 'ver_ckt_1',
        recipe_id: 'rec_chocolate_cake',
        version_number: 1,
        version_name: 'Original 12-Slice Recipe',
        hpp: 114875,
        hpp_per_portion: 9573,
        change_notes: '12 slice cake formulasi rich cocoa',
        ingredients_snapshot: [],
        status: 'ACTIVE',
        created_at: '2026-03-01T09:00:00Z',
      }
    ]
  }
];

// Clean zero cost ingredient item
initialRecipes[3].ingredients = initialRecipes[3].ingredients?.filter(i => i.cost > 0);

export const initialSalesMenus: SalesMenu[] = [
  {
    id: 'menu_agp_nasi',
    code: 'MNU-AGP-01',
    name: 'Paket Ayam Geprek + Nasi Hangat',
    category_id: 'cat_menu_main',
    recipe_id: 'rec_ayam_geprek',
    recipe_name: 'Ayam Geprek Sambal Bawang',
    selling_price: 28000,
    hpp: 10600, // 8700 (ayam geprek) + 1900 (nasi pulen)
    food_cost: 37.9,
    gross_profit: 17400,
    margin: 62.1,
    photo_url: '/src/assets/images/dish_ayam_geprek_1791109817096.jpg',
    status: 'ACTIVE',
    created_at: '2026-01-25T12:00:00Z',
    updated_at: '2026-09-30T15:00:00Z',
  },
  {
    id: 'menu_nsg_spesial',
    code: 'MNU-NSG-02',
    name: 'Nasi Goreng Spesial Telur Ceplok',
    category_id: 'cat_menu_main',
    recipe_id: 'rec_nasi_goreng',
    recipe_name: 'Nasi Goreng Spesial Resto',
    selling_price: 26000,
    hpp: 8200,
    food_cost: 31.5,
    gross_profit: 17800,
    margin: 68.5,
    photo_url: '/src/assets/images/dish_nasi_goreng_1791109832554.jpg',
    status: 'ACTIVE',
    created_at: '2026-02-12T10:00:00Z',
    updated_at: '2026-09-28T16:00:00Z',
  },
  {
    id: 'menu_mie_ayam_komplit',
    code: 'MNU-MAY-03',
    name: 'Mie Ayam Komplit Pangsit Kuah',
    category_id: 'cat_menu_main',
    recipe_id: 'rec_mie_ayam',
    recipe_name: 'Mie Ayam Komplit Gurih',
    selling_price: 27000,
    hpp: 9150,
    food_cost: 33.9,
    gross_profit: 17850,
    margin: 66.1,
    photo_url: '/src/assets/images/dish_mie_ayam_1791109845039.jpg',
    status: 'ACTIVE',
    created_at: '2026-02-18T15:00:00Z',
    updated_at: '2026-09-29T10:00:00Z',
  },
  {
    id: 'menu_choco_cake_slice',
    code: 'MNU-CKT-04',
    name: 'Chocolate Fudge Cake (Single Slice)',
    category_id: 'cat_menu_dessert',
    recipe_id: 'rec_chocolate_cake',
    recipe_name: 'Artisan Dark Chocolate Fudge Cake',
    selling_price: 35000,
    hpp: 9573,
    food_cost: 27.4,
    gross_profit: 25427,
    margin: 72.6,
    photo_url: '/src/assets/images/dish_chocolate_cake_1791109868136.jpg',
    status: 'ACTIVE',
    created_at: '2026-03-05T09:00:00Z',
    updated_at: '2026-09-25T11:00:00Z',
  }
];

export const initialPriceHistory: IngredientPriceHistory[] = [
  {
    id: 'ph_1',
    ingredient_id: 'ing_tepung',
    ingredient_name: 'Tepung Terigu Protein Tinggi',
    old_price: 12250,
    new_price: 14000,
    change_percent: 14.29,
    effective_date: '2026-09-30T11:15:00Z',
    supplier: 'PT Pangan Sumber Makmur',
    reason: 'Kenaikan tarif gandum impor dan biaya logistik pabrik',
    created_at: '2026-09-30T11:15:00Z',
  },
  {
    id: 'ph_2',
    ingredient_id: 'ing_cabai',
    ingredient_name: 'Cabai Rawit Merah',
    old_price: 38000,
    new_price: 45000,
    change_percent: 18.42,
    effective_date: '2026-10-01T07:45:00Z',
    supplier: 'Pasar Induk Kramat Jati',
    reason: 'Faktor musim hujan dan pasokan petani berkurang',
    created_at: '2026-10-01T07:45:00Z',
  },
  {
    id: 'ph_3',
    ingredient_id: 'ing_ayam',
    ingredient_name: 'Ayam Fillet / Karkas',
    old_price: 34000,
    new_price: 36000,
    change_percent: 5.88,
    effective_date: '2026-09-28T09:30:00Z',
    supplier: 'CV Mitra Unggas Segar',
    reason: 'Kenaikan harga pakan ayam jagung broiler',
    created_at: '2026-09-28T09:30:00Z',
  }
];

export const initialSettings: AppSettings = {
  app_name: 'CULINOVA Recipe & Food Cost Management',
  currency: 'IDR',
  food_cost_target: 35,
  margin_target: 65,
  food_cost_threshold_low: 28,
  food_cost_threshold_high: 38,
  price_rounding: '500',
  date_format: 'DD MMM YYYY',
  google_sheet_id: process.env.GOOGLE_SHEET_ID || '',
  google_client_email: process.env.GOOGLE_CLIENT_EMAIL || '',
  google_is_connected: Boolean(process.env.GOOGLE_SHEET_ID && process.env.GOOGLE_CLIENT_EMAIL),
};

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log_1',
    user: 'Gabriel (Administrator)',
    action: 'PRICE_CHANGE',
    module: 'Ingredients',
    record_id: 'ing_tepung',
    details: 'Updated Tepung Terigu price from Rp12.250 to Rp14.000 (+14.29%)',
    timestamp: '2026-09-30T11:15:00Z'
  },
  {
    id: 'log_2',
    user: 'Gabriel (Administrator)',
    action: 'VERSION_ACTIVATE',
    module: 'Recipes',
    record_id: 'rec_ayam_geprek',
    details: 'Activated Ayam Geprek Version 2 (HPP Rp8.700)',
    timestamp: '2026-09-30T14:00:00Z'
  },
  {
    id: 'log_3',
    user: 'Gabriel (Administrator)',
    action: 'PRICE_CHANGE',
    module: 'Ingredients',
    record_id: 'ing_cabai',
    details: 'Updated Cabai Rawit Merah price from Rp38.000 to Rp45.000 (+18.42%)',
    timestamp: '2026-10-01T07:45:00Z'
  },
  {
    id: 'log_4',
    user: 'Gabriel (Administrator)',
    action: 'UPDATE',
    module: 'Sales Menu',
    record_id: 'menu_agp_nasi',
    details: 'Recalculated HPP for Paket Ayam Geprek + Nasi to Rp10.600',
    timestamp: '2026-10-01T08:00:00Z'
  }
];
